### ISSUE TITLE
Skin Shortcuts integration job-list

### ISSUE THREAD

**Issue by Ignoble61** [Ignoble61/skin.aeon.madnox#1]
- [x] More complex backgrounds - live cases, will most of rest be covered by Skin Helper backgrounds...?
- [x] Fix font for widget label (two lines should be able to be seen)
- [x] Decide + implement how artwork choices will be limited
- [x] Fallback images when widget artwork isn't present
- [ ] Use correct flag images for list widget layout
- [ ] Choice of BD cases/use existing MadNox cases for widgets
- [x] Use additional submenu as a widget
- [x] System info widget
- [x] Sort widgets randomly (a nice-to-have :wink:)
- [ ] Widget label not always showing (reported with Next Aired TV Shows widget, widget info panel)
- [x] Fix playlist infolines

**Comment by Ignoble61** [comment]
Different layout options available for all widgets:-
 - Panel (4x3 fanart, or 1x1 icon)
 - Classic (4x3, fanart, or 1x1 icon, single image on left)
 - Info (Poster/icon w/information)

Additional layouts available for tv/movie widgets:-
 - Poster
 - Logo/Clearart/Landscape (16x9)
 - Banner

**Comment by Ignoble61** [comment]
As the original job list has been completed, updated job list with 'fit and finish' tasks from the MadNox thread. I'll try to keep it up-to-date as new issues are raised so there's a central place to see what still needs to be done :)

**Comment by MadMikeDoc** [comment]
This is done as well: Use correct flag images for list widget layout. Mr. V has the relevant files for his new branch.

I tried to look into this but couldn't quite figure out how the cases work in the new widgets to be able to add another option or to update the paths to the relevant folders in the media folder for existing madnox cases.

Mike

**Comment by Ignoble61** [comment]
You have push rights to the repo. As well as letting you submit code directly to the branch, you can click the empty checkbox next to the issue you've fixed ;)

(Not that this lost is of any import now Mr. V has moved onto his widgets v3.5)
